backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "src/img/uploads" # path where uploaded files should be saved, relative to the base of the repo
public_folder: "/img/uploads" # relative to the base of the built site

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true


collections:
  # Our portfolio
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Project" # Used in the UI
    folder: "src/portfolio" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Product", name: "product", widget: "string", default: "Web - application" }
      - { label: "Result", name: "result", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["development", "management"] }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Featured Image"
        name: "img"
        widget: "image"
        choose_url: true
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }